---
- name: ensure necessary yum packages are installed
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{rvm.required_packages}}"
  become: true
  when: ansible_os_family == "RedHat"

- name: ensure necessary apt packages are installed
  apt:
    name: "{{ item }}"
    state: present
  become: true
  with_items: "{{rvm.required_packages}}"
  when: ansible_os_family == "Debian"
